FROM nginx:alpine

COPY . /usr/share/nginx/html
EXPOSE 80

# build     docker build -t pwa-frontend .
# run       docker run -d -p 3001:80 pwa-frontend
# export    docker save -o pwa-frontend.tar pwa-frontend